# This is a basic workflow to help you get started with Actions

name: Deploy GH Pages

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          # GitHub repository where assets will be deployed (default current)
          repo: "https://github.com/Skillz4Killz/gamer-landing"
          # Git branch where assets will be deployed
          target_branch: "master"
          # Create incremental commit instead of doing push force
          keep_history: true
          # Allow an empty commit to be created
          allow_empty_commit: false
          # Build directory to deploy
          build_dir: "build"
          # Write the given domain name to the CNAME file
          fqdn: discordbot.mod.land
          # Allow Jekyll to build your site
          jekyll: false
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
